<?php include $header ; ?>
<?php echo $nav ; ?>
<table>
    <th>
        <tr><td>Country</td><td>ISO Code 2</td><td>ISO Code 3</td></tr>
    </th>
    <?php foreach($location->rows() as $row) : ?>
        <tr>
            <td><?php echo $row->name ; ?></td>
            <td><?php echo $row->iso_code_2 ; ?></td>
            <td><?php echo $row->iso_code_3 ; ?></td></tr>
    <?php endforeach ; ?>
</table>
<?php include $footer ; ?>