<?php include $header ; ?>
<?php echo $nav ; ?>
    <a href="<?php echo $basepath ; ?>/location/addzoneareas">Add Zone Area</a>
    <table>
        <th>
            <tr style="background-color: yellow"><td>Area</td><td>Code</td><td>&nbsp;</td></tr>
        </th>
        <?php foreach($location_zone_areas->rows() as $row) : ?>
            <tr>
                <td><?php echo $row->name ; ?></a></td>
                <td><?php echo $row->code ; ?></td>
                <td><a href="<?php echo $basepath ; ?>/location/editzonerea/<?php echo $row->id ; ?>">Edit</a> | <a href="<?php echo $basepath ; ?>/location/deletezone/<?php echo $row->id ; ?>">Disable</a></td>
            </tr>
        <?php endforeach ; ?>
    </table>
<?php include $footer ; ?>